Gearbox
yearn/yearn-exporter pull request #278
Opened 2022-03-29 01:15 UTC by AmantayAbdurakhmanov

2022-03-29 20:59 UTC, BobTheBuidler commented
I've tested this, works fine. 
@banteg could you also validate the math here since the stakes are high?

2022-04-04 20:14 UTC, BobTheBuidler commented
@AmantayAbdurakhmanov I committed one more change to your fork after reviewing with @mariuspod , everything looks good to go now. Could you rebase your branch on master once more and then I can merge? Thanks!

2022-04-04 20:20 UTC, mariuspod requested changes

2022-04-04 20:20 UTC, mariuspod commented on yearn/partners/snapshot.py
> +            tvl = sum(balance for balance in balances_at_block) / Decimal(vault.scale)
change to `sum(balance / Decimal(vault.scale) for balance in balances_at_block)`

2022-04-04 20:21 UTC, mariuspod approved these changes
LGTM!

2022-04-04 23:55 UTC, merged