fix: more convex fixes
yearn/yearn-exporter pull request #284
Opened 2022-03-30 16:48 UTC by jstashh

* Ensure strategies are in the correct order - curve first, then convex
* Correct price calculation for `rKP3R`

2022-03-30 16:48 UTC, jstashh commented on yearn/apy/curve/simple.py
> +                if reward_token == addresses[chain.id]['rkp3r_rewards']:
forgot to add this custom logic for rKP3R

2022-03-31 19:32 UTC, mariuspod requested changes

2022-04-05 11:57 UTC, jstashh commented on yearn/apy/curve/simple.py
> +                if reward_token == addresses[chain.id]['rkp3r_rewards']:
Added a guard to the entry point of this file, as we access `chain.id` in multiple places - 42ba267

2022-04-05 12:00 UTC, jstashh commented on yearn/apy/curve/simple.py
> +                if reward_token == addresses[chain.id]['rkp3r_rewards']:
Refactored addresses[chain.id] into its own variable in 573fe42af66655ea11deee3a897d40312e9a4791

2022-04-08 09:41 UTC, mariuspod approved these changes
Tested manually and with some unit and integration tests here:
https://github.com/jstashh/yearn-exporter/pull/2

2022-04-11 12:52 UTC, merged